---

- name: DESKTOP | Media | Uninstall
  hosts: desktop
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: audacity, state: 'uninstall' }
    - { role: avidemux, state: 'uninstall' }
    - { role: kodi, state: 'uninstall' }
    - { role: simplescreenrecorder, state: 'uninstall' }
    - { role: videocodec, state: 'uninstall' }
    - { role: vlc, state: 'uninstall' }

