---

- name: DESKTOP | Admin | Install
  hosts: desktop
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: cups, state: 'install' }
    - { role: filezilla, state: 'install' }
    - { role: gigolo, state: 'install' }
    - { role: gnomeextra, state: 'install' }
    - { role: gparted, state: 'install' }
    - { role: seahorse, state: 'install' }
    - { role: terminator, state: 'install' }
    - { role: virtualbox, state: 'install' }
    - { role: x2goclient, state: 'install' }

