---

- name: DESKTOP | Admin | Uninstall
  hosts: desktop
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: cups, state: 'uninstall' }
    - { role: filezilla, state: 'uninstall' }
    - { role: gigolo, state: 'uninstall' }
    - { role: gnomeextra, state: 'uninstall' }
    - { role: gparted, state: 'uninstall' }
    - { role: seahorse, state: 'uninstall' }
    - { role: terminator, state: 'uninstall' }
    - { role: virtualbox, state: 'uninstall' }
    - { role: x2goclient, state: 'uninstall' }

