---

- name: DESKTOP | Office | Install
  hosts: desktop
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: calibre, state: 'install' }
    - { role: courrielleur, state: 'install' }
    - { role: firefox, state: 'install' }
    - { role: keepassxc, state: 'install' }
    - { role: libreoffice, state: 'install' }
    - { role: owncloudclient, state: 'install' }
    - { role: retext, state: 'install' }
    - { role: thunar, state: 'install' }
    - { role: thunderbird, state: 'install' }

